/* SPDX-License-Identifier: MIT
 * Execute verbatim production callback bodies with GTK/Wayland boundaries
 * mocked. This tests thread ownership and unlock policy, not visual rendering.
 */
#define _POSIX_C_SOURCE 200809L
#include <assert.h>
#include <pthread.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "auth.h"

typedef int gboolean;
typedef unsigned guint;
typedef size_t gsize;
typedef void *gpointer;
#define TRUE 1
#define FALSE 0
#define G_SOURCE_REMOVE 0
#define G_APPLICATION(x) (x)
#define GTK_ENTRY(x) (x)
#define GTK_LABEL(x) (x)
#define GPOINTER_TO_INT(x) ((int)(intptr_t)(x))
#define GINT_TO_POINTER(x) ((void *)(intptr_t)(x))
#define _(x) (x)
struct Window { void *input_field, *error_label; };
struct Array { guint len; struct Window *data[2]; };
#define g_array_index(a, type, i) ((a)->data[i])
struct GtkLock {
	guint draw_time_source, idle_hide_source;
	gboolean authenticated;
	void *app, *lock;
	struct Array *windows;
	struct Window *focused_window;
	const char *unlock_command;
};
static struct GtkLock *gtklock;
static pthread_t ui_thread;
static int quits, unlocks, syncs, commands, enables, cleared, failures, focused, unmarked;
static size_t secret_size;
static enum pwcheck pam_result;
static gboolean (*pending)(gpointer);
static gpointer pending_data;
static void on_ui(void) { assert(pthread_equal(pthread_self(), ui_thread)); }
static void g_source_remove(guint id) { on_ui(); assert(id > 0); }
static void g_application_unmark_busy(void *app) { on_ui(); assert(app); ++unmarked; }
static void g_application_quit(void *app) { on_ui(); assert(app); ++quits; }
static void gtk_session_lock_lock_unlock_and_destroy(void *lock) { on_ui(); assert(lock); ++unlocks; }
static void *gdk_display_get_default(void) { on_ui(); return gtklock; }
static void gdk_display_sync(void *display) { on_ui(); assert(display); ++syncs; }
static void exec_command(const char *command) { on_ui(); assert(command); ++commands; }
static void window_set_busy(struct Window *win, gboolean busy) { on_ui(); assert(win && !busy); ++enables; }
static void gtk_entry_set_text(void *entry, const char *text) { on_ui(); assert(entry && !*text); ++cleared; }
static void gtk_label_set_text(void *label, const char *text) { on_ui(); assert(label && !strcmp(text, "Login failed")); ++failures; }
static void gtk_entry_grab_focus_without_selecting(void *entry) { on_ui(); assert(entry); ++focused; }
static void g_free(void *ptr) {
	assert(!pthread_equal(pthread_self(), ui_thread));
	for(size_t i = 0; i < secret_size; ++i) assert(((unsigned char *)ptr)[i] == 0);
	free(ptr);
}
static guint g_idle_add(gboolean (*callback)(gpointer), gpointer data) {
	assert(!pthread_equal(pthread_self(), ui_thread) && !pending);
	pending = callback;
	pending_data = data;
	return 1;
}
enum pwcheck auth_pw_check(const char *password) {
	assert(!pthread_equal(pthread_self(), ui_thread));
	assert(!strcmp(password, "test-only-password"));
	return pam_result;
}

/* Generated by the runner from the actual patched upstream source files. */
#include TDVP_UI_CALLBACKS

static void run_case(enum pwcheck result, guint outputs) {
	struct Window windows[] = {{(void *)1, (void *)2}, {(void *)3, (void *)4}};
	struct Array array = {outputs, {windows, windows + 1}};
	struct GtkLock state = {.app = &array, .lock = &array, .windows = &array,
		.focused_window = outputs ? windows : NULL, .unlock_command = "test-only",
		.draw_time_source = 1, .idle_hide_source = 2};
	gtklock = &state;
	quits = unlocks = syncs = commands = enables = cleared = failures = focused = unmarked = 0;
	pending = NULL;
	pam_result = result;
	char *password = strdup("test-only-password");
	assert(password);
	secret_size = strlen(password) + 1;
	pthread_t worker;
	assert(pthread_create(&worker, NULL, window_pw_wait, password) == 0);
	assert(pthread_join(worker, NULL) == 0);
	assert(pending && quits == 0 && unlocks == 0 && !state.authenticated);
	assert(pending(pending_data) == G_SOURCE_REMOVE);
	assert(unmarked == 1);
	gtklock_shutdown(&state);
	assert(state.draw_time_source == 0 && state.idle_hide_source == 0);
	if(result == PW_SUCCESS) {
		assert(state.authenticated && quits == 1 && unlocks == 1 && syncs == 1 && commands == 1);
		assert(enables == 0 && failures == 0);
	} else {
		assert(!state.authenticated && quits == 0 && unlocks == 0 && syncs == 0 && commands == 0);
		assert(enables == (int)outputs && cleared == (int)outputs && failures == (int)outputs);
		assert(focused == (outputs ? 1 : 0));
	}
}
int main(void) {
	ui_thread = pthread_self();
	for(guint outputs = 0; outputs <= 2; ++outputs) {
		for(int result = PW_WAIT; result <= PW_MESSAGE; ++result) run_case(result, outputs);
	}
	/* SIGTERM invokes shutdown without an authentication result. */
	struct GtkLock stopped = {0};
	unlocks = syncs = commands = 0;
	gtklock_shutdown(&stopped);
	assert(unlocks == 0 && syncs == 0 && commands == 0);
	puts("PASS gtklock production callbacks: 15 result/output cases, worker isolation, secret wiping, unauthenticated shutdown");
	return 0;
}
