#!/bin/sh
set -eu

die() {
	echo "vpl-desktopctl: $*" >&2
	exit 2
}

require_percent() {
	case "$1" in
		''|*[!0-9]*) die "percentage must be an integer" ;;
	esac
	[ "$1" -ge 0 ] && [ "$1" -le 100 ] || die "percentage must be 0 through 100"
}

set_volume() {
	value="$1"
	require_percent "$value"
	/usr/bin/amixer -q set Master "$value%" ||
		/usr/bin/amixer -q set PCM "$value%" ||
		die "no writable ALSA Master or PCM control"
}

set_brightness() {
	target="$1"
	value="$2"
	require_percent "$value"
	case "$target" in
		display) /usr/bin/vpl-hwctl set display-brightness "$value" ;;
		keyboard) /usr/bin/vpl-hwctl set keyboard-brightness "$value" ;;
		*) die "unknown brightness target" ;;
	esac
}

export_logs() {
	user="$1"
	home="$(getent passwd "$user" | cut -d: -f6)"
	[ -n "$home" ] && [ -d "$home" ] || die "unknown home directory"
	uid="$(id -u "$user")"
	gid="$(id -g "$user")"
	stamp="$(date -u +%Y%m%dT%H%M%SZ)"
	dir="$(mktemp -d)"
	trap 'rm -rf "$dir"' EXIT HUP INT TERM
	/bin/journalctl -b --no-pager > "$dir/journal.txt" 2>&1 || true
	/bin/dmesg > "$dir/dmesg.txt" 2>&1 || true
	/usr/sbin/ip address > "$dir/ip-address.txt" 2>&1 || true
	/usr/sbin/ip route > "$dir/ip-route.txt" 2>&1 || true
	/usr/bin/nmcli -f GENERAL.STATE,GENERAL.CONNECTION,IP4.ADDRESS,IP4.GATEWAY device show wlan0 > "$dir/wifi-state.txt" 2>&1 || true
	install -d -o "$uid" -g "$gid" "$home/Downloads"
	out="$home/Downloads/tdvp-support-$stamp.tar.gz"
	tar -C "$dir" -czf "$out" .
	chown "$uid:$gid" "$out"
	echo "$out"
}

[ "$#" -ge 1 ] || die "missing command"
case "$1" in
	volume)
		[ "$#" -eq 2 ] || die "volume requires a percentage"
		set_volume "$2"
		;;
	brightness)
		[ "$#" -eq 3 ] || die "brightness requires target and percentage"
		set_brightness "$2" "$3"
		;;
	export-logs)
		[ "$#" -eq 2 ] || die "export-logs requires a user"
		export_logs "$2"
		;;
	reboot)
		[ "$#" -eq 1 ] || die "reboot takes no arguments"
		exec /bin/systemctl reboot
		;;
	poweroff)
		[ "$#" -eq 1 ] || die "poweroff takes no arguments"
		exec /bin/systemctl poweroff
		;;
	*) die "unknown command: $1" ;;
esac
